completion.go

Fixes typo in json serialization (logobs -> logprobs) and adds LogprobResult type for results.
Also changes CompletionRequest.Stop to a []string to match the API (so more than one stop sequence can be used).

Add logprob support

---

completion.go

Fix weird 'C' in CompletionResponse struct

---

README.md

Sorry for not including this in the previous PR.. the example in the docs includes the 'C' as well, so I don't think it would compile.

Replace Cyrillic 'C' in README

---

api.go

To set the `OpenAI-Organization` header, if appropriate.
https://beta.openai.com/docs/api-reference/authentication

api.go: add constructor variant for organizations

---

answers.go
completion.go

Hey, was playing around with openAI and figured I´d add my additions upstream.
Thanks for the module, it helped me a bunch!

Adding Answer request AND adding best_of option to Completion. 

---

answers.go
api.go
api_test.go
error.go
files.go

- Added a new files endpoint for:
- list files
- get file
- Corrected documents double array bug in answers endpoint
- Added error message if exists in API response

Files endpoint + answers endpoint bug fix + API error messages

---

completion.go

OpenAI recently added the ability to use a fine-tuned model to generate completions with GPT-3.
This PR adds a function to implement this feature, which uses a different endpoint than CreateCompletion.
See here for the format: https://beta.openai.com/docs/guides/fine-tuning/use-a-fine-tuned-model
Lmk if any additional comments etc would be useful here.

Add CreateCompletionWithFineTunedModel function

---

moderation.go

Added a file to support the new [Moderation endpoint](https://beta.openai.com/docs/guides/moderation/moderation).
Previously mentioned in https://github.com/sashabaranov/go-gpt3/issues/19#issue-1290828426.

rev: added a file to support moderations endpoint

---

README.md
api_test.go
completion.go
embeddings.go
search.go

OpenAI has moved its completions endpoint and embedding endpoint away from including the engineID as a part of the URL query string. This PR aims to close #27 by removing the `engineID` parameter from the calls, forcing users to specify them in the Request structs.
Signed-off-by: Oleg <97077423+RobotSail@users.noreply.github.com>

Migrate From Old Completions + Embedding Endpoint

---

.golangci.yml
Makefile
api.go
api_test.go
common.go
completion.go
edits.go
embeddings.go
engines.go
files.go
moderation.go
search.go

This PR introduces the following changes:
- `EditsUsage` and `CompletionsUsage` are removed and `Usage` is created as a separate type in `common.go` 
- Some available models are added as constants for the completions endpoint so that they can be included in the `CompletionRequest.Model` field
- A mocked server is added for testing the edits and completions endpoint 
- Makefile along with targets to downloads to install golangci-lint
- Fixes up the code so that the linter will pass
- Includes the golden [golangci-lint file](https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322)
Note: not all of the endpoints have been implemented with the mocked server yet, and we should continue to do so as more changes are iterated on in this project. 
This PR aims to close out #30, however …

Add OpenAI Mock Server

---

completion.go

Open AI Announced their new completion model `text-davinci-003` This is not available for any other endpoints at the moment.
https://beta.openai.com/docs/models/overview

Add new text-davinci-003 model to constants

---

completion.go

Add "Suffix" to "CompletionRequest" to support the new insert mode.
Insert mode info: https://openai.com/blog/gpt-3-edit-insert/
New Completion Request API Reference: https://beta.openai.com/docs/api-reference/completions/create#completions/create-prompt

Add Suffix to CompletionRequest for insert mode

---

embeddings.go

Just earlier today OpenAI released "text-similarity-ada-002" Their first v2 embeddings model. 
https://openai.com/blog/new-and-improved-embedding-model/
https://beta.openai.com/docs/guides/embeddings/embedding-models
This replaces the need for the 5 separate text models. It outperforms all except for davinci-001 on one specific test set. It is also more cost efficient.
(I should have waited one more hour before my last PR. Who would have known!)

New Ada Similarity Model

---

api_test.go

Added moderation endpoint test

---

stream.go

An endless loop occurs if ReadBytes() returns non-IO error, such as network interrupt.
```go
waitForData:
line, err := stream.reader.ReadBytes('\n')
if err != nil {
if errors.Is(err, io.EOF) {
return
}
}
var headerData = []byte("data: ")
line = bytes.TrimSpace(line)
if !bytes.HasPrefix(line, headerData) {
emptyMessagesCount++
if emptyMessagesCount > emptyMessagesLimit {
err = ErrTooManyEmptyStreamMessages
return
}
goto waitForData
}
```

Fix endless loop while network error

---

api.go
go.mod

Non-breaking changes which allow for a configurable "Transport" (language which was already used in the project, really a `*http.Client`).
This allows for setting a custom `RoundTripper` or using `github.com/hashicorp/go-retryablehttp`:
```go
transport := retryablehttp.NewClient().StandardClient()
c := gogpt.NewClientWithTransport(openAIAPIKey, transport)
```
With the recent stability issues and load of the OpenAI API this is necessary to use the module in a production environment.

Configurable Transport

---

api.go
api_test.go
completion_test.go
config.go
edits_test.go
files_test.go
image_test.go
moderation_test.go
stream.go
stream_test.go

This PR aims to make the client completely configurable, following up #75 and #4. It also fixes #70.
The idea is to pass-by-value config struct, which would be encapsulated inside the client.
Here we preserve the standard way of creating clients as `client := gogpt.NewClient("auth token")` and add a new way of configuring clients:
```go
config := DefaultConfig("auth token")
config.BaseURL = server.URL + "/v1"
config.OrgID = "my org id"
config.HTTPClient.Transport = &tokenRoundTripper{
test.GetTestToken(),
http.DefaultTransport,
}
config.EmptyMessagesLimit = 10000
client := NewClientWithConfig(config)
ctx := context.Background()
```

Better configuration

---

api_test.go
chat.go

I found an undocumented possibility - for messages of the gpt-3.5 model, you can additionally specify the "name" property. This additional feature is useful for chats with multiple participants.
Found in the examples of the official library for python (Item No. 6 - Counting tokens for chat API calls): [https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken .ipynb](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb)

add "name" property for ChatCompletionMessage

---

embeddings.go

use float32 in embeddings

---

image.go
image_test.go

1. Fix issue #149 
2. Add image variation implementation according to 
https://platform.openai.com/docs/api-reference/images/create-variation

Add image variation implementation and fix #149

---

chat.go
completion.go

This PR adds support for the GPT-4-32K and GPT-4-32K-0314 models by adding three new constants to the list of GPT models and adding the new models to the switch statements in the CreateChatCompletion and CreateCompletion functions. The PR also removes unnecessary code that checked for invalid models, as the new models are valid. The changes in this PR do not introduce any new issues and successfully add support for the new models.
Changes Made:
Added three new constants for GPT-4-32K and GPT-4-32K-0314 models
Added new models to switch statements in CreateChatCompletion and CreateCompletion functions
Removed unnecessary code that checked for invalid models

Add support for GPT-4-32K and GPT-4-32K-0314 models

---

README.md

When using `ChatCompletionStream`, I implemented the code by referencing the following test.
https://github.com/sashabaranov/go-openai/blob/a8acb5f63bcb4d5966d1a57709a32315eeff1ff9/chat_stream_test.go#L53
As it seems that #164 encountered the same issue, I  added an example of usage to the README.

Add readme example of ChatGPT streaming completion

---

chat_stream.go
chat_stream_test.go
error_accumulator.go
error_accumulator_test.go
stream.go
stream_reader.go
stream_test.go
unmarshaler.go

fix: stream return EOF when openai return error

---

chat.go
chat_stream.go
chat_stream_test.go
chat_test.go
completion.go
completion_test.go
request_builder_test.go
stream.go
stream_test.go

- Add model check for `CreateCompletionStream` and `CreateChatCompletionStream`.
- Correct model check in `CreateCompletion`.

refactor: Refactor endpoint and model compatibility check

---

audio.go

This PR solve the above issue:
- #175 
In some cases, the audio file opened for reading is not closed, making it impossible to remove it.
The `f.Close` call was added at the end of the execution of the `audioMultipartForm` function.

fix: added defer to close audio file

---

chat_stream.go

add ChatCompletionStream Usage return

add ChatCompletionStream Usage return

---

completion.go
completion_test.go
request_builder_test.go
stream.go

solve iusse #201   i think this feature is useful
i closed  pr #210   because  I think there are too many unnecessary changes, here is a more concise change to implement
```go
c := openai.NewClient("your token")
ctx := context.Background()
// test CreateCompletion
reqNor := CompletionRequest{
Prompt:    []string{"Lorem ipsum", "Lorem ipsum", "Lorem ipsum"}, //use string or []string 
Model:     GPT3Curie,
MaxTokens: 5,
}
resp, err := c.CreateCompletion(ctx, reqNor)
checks.NoError(t, err, "CreateCompletion returned error")
if err == nil {
for _, c := range resp.Choices {
t.Logf("index =`%d`,text is `%s` \n", c.Index, c.Text)
}
}
```
`Prompt`   can be assigned `string` or `[]string` type
Streaming is also supported
```go
c := openai.NewClient("your token")
ctx := context.Background()
// test …
```

CompletionBatchingRequestSupport

---

chat_stream.go

In the pr on [215](https://github.com/sashabaranov/go-openai/pull/215). I found that I used the wrong way to add Usage. when `stream = true` will not  return `Usage` filed.
`Usage` should be calculated by the user himself.

to fix v1.5.8 Usage return 

---

api_test.go
error.go

Based on [this comment](https://github.com/sashabaranov/go-openai/pull/247#issuecomment-1507658375), this PR implements the custom JSON Unmarshaller interface to handle numbers, strings, or any other type that might be returned by the API.
Also fixed a bug where the skipped production test should EXPECT an error, rather than the opposite.

Implement Unmarshaller interface. Resolves #244

---

README.md
audio.go
audio_test.go
client.go
client_test.go

Closes https://github.com/sashabaranov/go-openai/issues/143
Allows users to add a `Format: ` argument to the request to get captions from the audio apis.
Demonstration (using the same code added for README)
https://user-images.githubusercontent.com/4222666/232965446-78a47bc5-d7eb-4439-a161-3ff13f2600ff.mov
Broke `decodeResponse` out of client, because cyclomatic complexity  got above 20 with the string response changes.
Added tests for `decodeResponse` to not decrease code coverage

Adds support for audio captioning with Whisper

---

api_internal_test.go
client.go

Fixing missing OrgId assignment issue in the ChatCompletionStream

---

client.go
client_test.go

Fix: OpenAI or Azure returns an undefined error message return
#280

 Fix OpenAI or Azure returns an undefined error message return

---

api_test.go

This pull request addresses and resolves issue #296 by removing the dependency on httpbin from the TestRequestError function.

Resolve issue #296: Remove httpbin dependency from TestRequestError

---

README.md
client.go
client_test.go
error.go

Resolves https://github.com/sashabaranov/go-openai/issues/292, https://github.com/sashabaranov/go-openai/issues/288
Maintains underlying error structs to allow consumers to utilize type conversion and create a defensive structure as defined by the Open AI error handling documentation.
It also slightly modifies the Error() functions to that they are responsible for converting the struct into an informational string versus just a fragment of its parent
Modifies only a single test that was missing a colon when all of the other tests have colons (including the RequestError Error function that was missing the colon that the other Error function included

maintain underlying error structs to allow for type conversion

---

audio.go
client.go
files.go
files_test.go
image.go
image_test.go
internal/form_builder.go
internal/form_builder_test.go
internal/test/utils/form_builder.go
internal/test/utils/form_builder_test.go

Move form_builder into internal pkg.

---

api_internal_test.go
config.go

Azure OpenAI API version 2023-05-15 has been released.
* [What's new in Azure OpenAI Service? \- Azure Cognitive Services \| Microsoft Learn](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/whats-new#azure-openai-chat-completion-general-availability-ga)
* [Azure OpenAI Service REST API reference \- Azure OpenAI \| Microsoft Learn](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#rest-api-versioning)
In response to the above announcement, I have updated the version specification.

Azure OpenAI API version 2023-05-15

---

README.md

Added in `unofficial` to the README to make it clear it's not official.

Update README.md to include "unofficial"

---

README.md

@sashabaranov I know there's an open PR with a more complex example for embeddings, but I think this gives a clear approach to anyone looking to implement embeddings quickly with Azure OpenAI

Update README.md with Azure OpenAI Embeddings example

---

audio.go
audio_test.go
image_test.go
internal/form_builder.go

This change adds an optional `io.Reader` to the `AudioRequest` structure. This addition makes this structure more versatile and allows you to use a different source other than an existing file from your filesystem. It also maintaining backwards compatibility.
I'd be glad to implement the same logic for the other Request types (`FileRequest`, `ImageEditRequest`, `ImageVariRequest`) in preferably subsequent PR's.

Implement optional io.Reader in AudioRequest (#303) (#265)

---

client_test.go
models.go
models_test.go

This is a pull request for #340, I implemented the Retrieve model API.
I added some test code to the `TestClientReturnsRequestBuilderErrors` function and golangci-lint threw the following error.
```
client_test.go:160:1: cognitive complexity 21 of func `TestClientReturnsRequestBuilderErrors` is high (> 20) (gocognit)
```
It seems that the cognitive complexity has increased. I refactored the `TestClientReturnsRequestBuilderErrors` function to reduce its cognitive complexity.  => https://github.com/sashabaranov/go-openai/pull/341/commits/b1cb1fec1295b16964b1f63ca2044dff12d43407

Support Retrieve model API (#340)

---

stream_reader.go
stream_test.go

@sashabaranov I'd appreciate your review on these changes.
This pull request introduces a refactor to the Recv method in the streamReader type, which improves code readability and maintainability.
- Replaced label with for block
- Replaced goto with continue to restart the loop if the condition is met.
- Replaced short variable declaration with regular variable declaration due to scope issue
- [For is a block scoped while labels are not block scoped](https://go.dev/ref/spec#Goto_statements:~:text=to%20other%20identifiers%2C-,labels%20are%20not%20block%20scoped,-and%20do%20not)
These changes maintain the functionality of the Recv method, while improving the clarity of the control flow within the function. The goto statement can sometimes make the code hard to understand and maintain, hence …

Refactor streamReader: Replace goto Statement with Loop in Recv Method

---

chat_stream_test.go
client_test.go
error.go

Fix #343
Azure OpenAI error response seems to be `type` field missing sometimes. Error (`unexpected end of JSON input`) when parsing `type` in `APIError.UnmarshalJSON` function.
Example error response:
```
{
"error":{
"code":"429",
"message":"Requests to the Creates a completion for the chat message Operation under Azure OpenAI API version 2023-03-15-preview have exceeded token rate limit of your current OpenAI S0 pricing tier. Please retry after 17 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit."
}
}
```
**Note:**
I also considered changing the `type` field to a pointer, but decided against it because that would be a breaking changes.

fix json marshaling error response of azure openai (#343)

---

chat_stream.go
client.go
client_test.go
files.go
files_test.go
stream.go

This is a pull request for https://github.com/sashabaranov/go-openai/issues/347, I implemented the Retrieve file content API.
The return value of the `GetFileContent` function is `io.ReadCloser`.  Because library users flexibility in handling the response.

Support Retrieve file content API (#347)

---

completion.go

Added GPT3Dot5Turbo0613, GPT3Dot5Turbo16K, GPT40613, and GPT432K0613
models from [June update](https://openai.com/blog/function-calling-and-other-api-updates)
Issue #360

models: add *-0613 models

---

chat_test.go
internal/test/server.go
openai_test.go

Improve on (#356) issue to support wildcard URLs required by Azure API path structure
Add Azure ChatCompletions test cases including test of custom deployment name

Improve (#356) to support registration of wildcard URLs

---

chat.go

When using openai.JSONSchemaTypeArray, you must define and "Items" object, otherwise OpenAI will return a 400.

add items, which is required for array type

---

audio.go

Added "text" and "verbose_json" output formats.
See reference:
https://platform.openai.com/docs/api-reference/audio/create

audio: add items to AudioResponseFormat enum

---

api_test.go
error.go

Fix #381
**Context:**
Basically, it is a `string`. However, if the json schema of the `parameters` field is invalid, as shown below, it is likely to be an `array`.
```bash
$ curl https://api.openai.com/v1/chat/completions -u :$OPENAI_API_KEY -H 'Content-Type: application/json' -d '{
"model": "gpt-3.5-turbo-0613",
"messages": [
{"role": "user", "content": "What is the weather like in Boston?"}
],
"functions": [
{
"name": "get_current_weather",
"parameters": {
"type": "object"
}
}
]
}'
{
"error":{
"message":[
"Invalid schema for function 'get_current_weather': In context=(), object schema missing properties"
],
"type":"invalid_request_error",
"param":null,
"code":null
}
}
```

fix parsing error of api error response (#381)

---

README.md
api_integration_test.go

Use go build tags to split integration tests to prevent unexpected integration test runs.
Run tests using:
```
OPENAI_TOKEN=XXX go test -v -tags=integration ./api_integration_test.go
```

split integration test using go build tag

---

chat_stream_test.go
stream_reader.go

Occasionally, OpenAI may return the following error message:
```
data: {"error":{"message":"The server experienced an error while processing your request. We apologize for the inconvenience!", "type":"server_error", "param":null,"code":null)}
data: [DONE]
```
In such cases, the stream.Recv() function will return a successful status along with a zero-value response.

fix: chat stream returns an error response with a 'data: ' prefix

---

README.md

I'd like go-openai to declare that 1.18 or greater is required because it uses generics internally.

docs: add requires go version in README.md

---

api_internal_test.go
audio.go
chat.go
chat_stream.go
client.go
client_test.go
completion.go
edits.go
embeddings.go
engines.go
files.go
fine_tunes.go
image.go
internal/request_builder.go
internal/request_builder_test.go
models.go
models_test.go
moderation.go
stream.go
stream_test.go

`http.Request` creation and sending were duplicated, so they have been aggregated into a common function.
- `RequestBuilder#Build` function calls were aggregated into the `Client#newRequest` function.
- All public functions build `http.Request` in the `Client#newRequest` function.
- The sending of `http.Request` is now aggregated into the following three functions.
- `Client#sendRequest` function: marshalling the response into a structure
- `Client#sendRequestRaw` function: returns the Body of the response as is 
- `Client#sendRequestStream` function: use generics to specify a `streamable` type.

refactor: refactoring http request creation and sending

---

README.md
chat.go
chat_test.go
jsonschema/json.go

@sashabaranov When discussing #377 you made [a comment](https://github.com/sashabaranov/go-openai/pull/377#issuecomment-1596097407) about separating out the json schema definitions, which [I did in a subsequent commit](https://github.com/sashabaranov/go-openai/pull/377#issuecomment-1597897146). Although it was added to @stillmatic 's fork before #377 was accepted, it looks like that commit didn't make it into the final merge!
I am including it here for consideration.

move json schema to directory/package

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

@sashabaranov I've created a pull request template for bug reports. Could you please review the content of the template?

chore: add a pull request template

---

chat_test.go

Hello,
I have made modifications to chat_test.go as it was using deprecated FunctionDefine.

replace deprecated FunctionDefine in chat_test.go 

---

embeddings.go
embeddings_test.go

Addresses #240 
There may be a cleaner way to do this, but this is the best way I could think of quickly to not cause any breaking changes and to maintain some semblance of type checking for the user (instead of just changing the Input field type in EmbeddingRequest from string to interface{}).
Also modified the test case for it.
Thanks for all of the work you guys do on this project!

Allow embeddings requests to be tokens or strings

---

README.md

@sashabaranov 
Adding instructions on how to obtain the OpenAI API key in README solves the following problems:
1. **Ease and Convenience**: New developers can quickly understand how to obtain the API key, enabling them to start using the library faster.
2. **Preventing Misunderstandings**: Without clear instructions, developers could potentially follow incorrect steps, leading to wasted time or potential security risks.
3. **Reducing Queries**: By providing clear instructions, there's less need for developers to ask questions or make inquiries about obtaining the API key, freeing up time for the maintainers of the library.
**Tests**
None.
Issue: #73

docs: added instructions for obtaining OpenAI API key to README

---

completion.go
edits.go
embeddings.go

Implement OpenAI July 2023 Updates
Issue: #425

Implement OpenAI July 2023 Updates

---

chat.go
completion.go

I've added comments to clarify the values of LogitBias, as they were difficult to understand.
**Tests**
None
Issue: #129 
@sashabaranov

docs: explanation about LogitBias. (#129)

---

jsonschema/json.go
jsonschema/json_test.go

This PR solves issue #429.
PR to reproduce the problem: #430 
If the map in the Properties field of jsonschema.Definition is set to nil, initialize it to an empty map. Also, as jsonschema.Definition has a recursive structure that can contain jsonschema.Definition as a child, perform the nil check and initialization recursively.
**Tests**
I have tested that the Properties field is initialized with an empty map in all of the following cases.
- Empty Definition
- Definition properties set
- Nested Definition properties
- Complex nested Definition
- Array type Definition
Issue: #429

fix: function call error due to nil properties (429)

---

api_integration_test.go
jsonschema/json.go
jsonschema/json_test.go

The problem recurs when Parameters is a value instead of a pointer. MarshalJSON in Definition does not execute MarshalJSON if Definition is a value because the receiver is a pointer.
```
func (d *Definition) MarshalJSON() ([]byte, error)
```
Refs:
- https://github.com/sashabaranov/go-openai/pull/433#issuecomment-1629401793
- https://github.com/sashabaranov/go-openai/pull/433#issuecomment-1629430142
error message:
```
invalid schema for function 'func_name': None is not of type 'object' 
```
request to reproduce:
```
req := openai.ChatCompletionRequest{
Model: openai.GPT3Dot5Turbo,
Messages: []openai.ChatCompletionMessage{
{
Role:    openai.ChatMessageRoleUser,
Content: "What is the weather like in Boston?",
},
},
Functions: []openai.FunctionDefinition{{
Name: …
```

fix: invalid schema for function 'func_name': None is not of type 'object' (#429)(#432)

---

.github/workflows/close-inactive-issues.yml

Managing neglected issues manually proves to be an arduous issue. It is desirable to have a bot in place to automate the closure of such issues.
Set up closing-inactive-issues in GitHub Action.
Refs: https://docs.github.com/en/github-ae@latest/actions/managing-issues-and-pull-requests/closing-inactive-issues
**Tests**
None
Issue: #415

ci: set up closing-inactive-issues in GitHub Action (#415)

---

moderation.go
moderation_test.go

Currently there are only [two models available](https://platform.openai.com/docs/api-reference/moderations/create) for OpenAI /moderations endpoint, which are `text-moderation-stable` and `text-moderation-latest`. In the official python library `openai-python`. The method Moderation will check if the model param is in `VALID_MODEL_NAMES` and returns an error when it's not. 
```python
def _prepare_create(cls, input, model, api_key):
if model is not None and model not in cls.VALID_MODEL_NAMES:
raise ValueError(
f"The parameter model should be chosen from {cls.VALID_MODEL_NAMES} "
f"and it is default to be None."
)
instance = cls(api_key=api_key)
params = {"input": input}
if model is not None:
params["model"] = model
return instance, params
```
It would be great if we can add similar checks …

Check if the model param is valid for moderations endpoint

---

README.md

Added an example for usage of fine tune
example in readme file
Issue: #315

add example: fine tune

---

chat.go

Currently, the comment for the `Parameters` property in the `jsonschema.FunctionDefinition` struct says that you can pass in a `[]byte{}`. However, this does not work and you need to use `json.RawMessage()` instead. 
Just updated the comment :)
**Tests**
Not applicable!
Passing in `[]byte{}` leads to base64'd value

Update comment for `jsonSchema.FunctionDefinition`

---

chat.go
chat_stream.go

Added support for Azure openai 2023-07-01-preview API. This version of the API mainly adds data related to content security in the returned content. Such as `prompt_annotations` and `content_filter_results`
It is mainly to supplement the return parameters added by the new version API in the corresponding structs in the `chat_stream.go` and `chat.go` files. And these parameters are marked with omitempty to be compatible with the old version of api and openai's api
**Tests**
Test with common test cases
``` shell
curl "https://TEST.openai.azure.com/openai/deployments/gpt-35-turbo-16k/chat/completions?api-version=2023-07-01-preview"   -H "Content-Type: application/json"   -H "api-key: MY_KEY"   -d "{
>   \"messages\": …
```

Add support for azure openai new version API (2023-07-01-preview)

---

chat.go
chat_test.go

this PR added a `MarshalJSON` to `FinishReason`. 
`MarshalJSON` implemented `Marshaler` interface in package `encoding/json` 
If `FinishReason` is `FinishReasonNull` or empty string, we can render it as `null` instead of `"null"`.
**Tests**
```
c := &ChatCompletionChoice{
FinishReason: FinishReasonNull,
}
jsonBytes, _ := json.Marshal(c)
fmt.Println(string(jsonBytes)) // it will print { .... "finish_reason": null }
```
Since i am not sure is this PR expected, i didn't add a lot of test cases in *_test.go file in the PR. but it was test locally.

feat: make finish reason nullable in json marshal

---

README.md

I've added a "Frequently Asked Questions" section to the README. The aim is to reduce duplicated issues and reduce  communication costs.
**Tests**
None
Issue: #9, #62

docs: add Frequently Asked Questions to README.md

---

CONTRIBUTING.md
README.md

- Contributing Guidelines have been added. For details, refer to CONTRIBUTING.md.
- A link to CONTRIBUTING.md has been added in the README.md.
- The Integration Test section from README.md has been moved to CONTRIBUTING.md.
- The outlines for Installation and Usage in README.md have been aligned.
**Tests**
None
None

docs: Add Contributing Guidelines

---

client_test.go
fine_tuning_job.go
fine_tuning_job_test.go

This PR implements new [Fine Tuning Job API ](https://platform.openai.com/docs/api-reference/fine-tuning).

feat: implement new fine tuning job API

---

README.md
fine_tunes.go

On August 22nd, 2023, OpenAI [announced](https://openai.com/blog/gpt-3-5-turbo-fine-tuning-and-api-updates) the deprecation of the `/v1/fine-tunes` API will take place on January 4th, 2024. OpenAI [recommends](https://platform.openai.com/docs/guides/legacy-fine-tuning) all users migrate to the new `/v1/fine_tuning/jobs` API. The old API is now [legacy](https://platform.openai.com/docs/guides/legacy-fine-tuning).
New `FineTuningJob` API has been implemented in `fine_tuning_job.go`
This PR deprecates `FineTunes` API implementation and updates README documentation example.

Chore Deprecate legacy fine tunes API

---

client_test.go
models.go
models_test.go

With the deprecation of the fine-tunes endpoint, OpenAI moved the deletion of fine-tuned models to `DELETE /models/{model}`. This PR adds this new endpoint in `models.go`.
I reworked the code present in `fine_tunes.go` that was already written for deleting fine-tuned models. Because OpenAI organized the new delete under the "models" prefix, this code is now located in the `models.go` file.
**Tests**
The tests used for the previous fine-tune model delete were reworked to use the new endpoint.

added delete fine tune model endpoint

---

README.md
embeddings.go
embeddings_test.go

- Implement a DotProduct() method for the Embedding struct to calculate the dot product between two embeddings.
- Add a custom error type for vector length mismatch.
- Finish implementing the following requested changes from @sashabaranov:
```
We don't need two huge examples [see](https://github.com/sashabaranov/go-openai/pull/274/files#r1232058195) — Please make one small example without encoding/gob etc.
I'm not sure this change is relevant [here](https://github.com/sashabaranov/go-openai/pull/274/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L596)
Let's make DotProduct a method of Embedding struct [see](https://github.com/sashabaranov/go-openai/pull/274/files#r1232242888)
```
**Tests**
- Add unit tests to …

Add DotProduct Method and README Example for Embedding Similarity Search

---

fine_tuning_job.go
fine_tuning_job_test.go

Issue: #496 
Hyper parameter `n_epochs` can be either a string or a int value.
Develop a custom un/marshaller for `n_epochs` parameter.

fix: use any for n_epochs

---

audio.go
chat.go
chat_test.go
client.go
completion.go
edits.go
embeddings.go
engines.go
files.go
fine_tunes.go
fine_tuning_job.go
image.go
models.go
moderation.go

This branch adds headers to all opeanai http responses.
This was done embedding a struct `httpHeader` to each response struct. The `httpHeader` type has attached methods to set and get `http.Header`. The low level `sendRequest` uses a `Response` interface defining the `SetHeader` method of `httpHeader`.
**Tests**
`TestChatCompletionsWithHeaders` has been added to check a test header.

Feat Add headers to openai responses

---

completion.go

Added constants for new GPT models including `gpt-4-1106-preview`, `gpt-4-vision-preview` and `gpt-3.5-turbo-1106`.
The models were announced in the following blog post: https://openai.com/blog/new-models-and-developer-products-announced-at-devday

feat(completion): add constants for new GPT models

---

api_integration_test.go
audio_api_test.go
audio_test.go
chat_stream_test.go
chat_test.go
completion_test.go
config_test.go
edits_test.go
embeddings_test.go
engines_test.go
error_test.go
example_test.go
files_api_test.go
files_test.go
fine_tunes.go
fine_tunes_test.go
fine_tuning_job_test.go
image_api_test.go
jsonschema/json_test.go
models_test.go
moderation_test.go
openai_test.go
stream_test.go

Fix linter warning reported by golangci-lint.
Fixes #519

lint: fix linter warnings reported by golangci-lint

---

README.md

Document the OpenAI-recommended technique for using in tandem with 0 or low `Temperature` to improve reproducibility.

Doc ways to improve reproducability besides Temp

---

assistant.go
assistant_test.go
client_test.go

This branch implements [assistants API](https://platform.openai.com/docs/api-reference/assistants) 
Create a new implementation file dedicated to this API
**Tests**
Tests attached in `assistant_test.go`
Issue: #533

Feat Implement assistants API

---

chat.go
chat_stream.go

This branch adds support for [new fields](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools) `tools` and `tool_choice`
New types have been added to support new features

Feat Support tools and tools choice new fileds

---

chat.go

The field `ChatCompletionResponseFormat` must be a pointer
Issue: #541

Fix Use pointer for ChatCompletionResponseFormat

---

image.go
image_api_test.go

Updating the [/v1/images/generation](https://platform.openai.com/docs/api-reference/images/create) api with the new changes announced at [devday](https://openai.com/blog/new-models-and-developer-products-announced-at-devday).
Simply add new fields to `ImageRequest` & `ImageResponseDataInner` as well a bunch of new const's for supported options.
**Tests**
Added more fields to the existing `TestImages` test, as these are later unmarshaled. Although if you would like to see tests that simply assert marshalling I could add some, let me know.
Issue: https://github.com/sashabaranov/go-openai/issues/529

Support new fields for /v1/images/generation API

---

assistant.go
client.go

- OpenAI Assistant API needs a [Beta header](https://platform.openai.com/docs/assistants/overview/step-1-create-an-assistant)
- AssistantTool types can be simplified
- Add the header on Assistant APIs
- use only `AssistantTool` type with optional sub fields.

Fix Refactor assistant api

---

api_integration_test.go

The compilation of the integration test is broken. It seems to have regressed due to the refactoring in PR #[522](https://github.com/sashabaranov/go-openai/pull/522/files#diff-e746382823c9b7cef735e766c987a5523b86a0d1be3236000c5c3e3ddfd7c55bL12).
Imported "github.com/sashabaranov/go-openai" and fixed the reference error.
**Tests**
None
Issue: #547

test: fix compile error in api integration test

---

client_test.go
thread.go
thread_test.go

Describe the change
This branch implements [threads API](https://platform.openai.com/docs/api-reference/threads)
Describe your solution
Create a new implementation file dedicated to this API
Tests
tests attached in `thread_test.go`
Issue: https://github.com/sashabaranov/go-openai/issues/533

Feat Implement threads API

---

fine_tuning_job_test.go
internal/test/server.go

- go map access is not deterministic
- this can lead to a route: /foo/bar/1 matching /foo/bar before matching /foo/bar/1 if the map iteration go through /foo/bar first since the regex match wasn't bound to start and end anchors
- registering handlers now converts * in routes to .* for proper regex matching
- test server route handling now tries to fully match the handler route
This makes testing less flaky

fix test server setup:

---

chat.go

There are [missing fields](https://platform.openai.com/docs/api-reference/chat/streaming) in `tool_calls` object. Following the documentation the [chat completion chunk object](https://platform.openai.com/docs/api-reference/chat/streaming) has the `index` field also.
Just added missing fields
Issue: #555

fix: add missing fields in tool_calls

---

run.go

Metadata is an optional field per the api spec
https://platform.openai.com/docs/api-reference/runs/createRun

Add `json:"metadata,omitempty"` to RunRequest struct

---

client_test.go
speech.go
speech_test.go

Adds very basic support for `create_speech` endpoint. 
See also https://platform.openai.com/docs/api-reference/audio/createSpeech and https://platform.openai.com/docs/guides/text-to-speech.
This is an extremely minimal approach that returns the http body (`io.ReadCloser`). An additional method that saves the result directly to a file is likely to be useful. For streaming, having the raw chunks is most helpful. The test includes an example for saving to file.
I've added the relevant constants, and the basic API should work, could use more tests for sure. 
**Tests**
I likely don't have time to write the necessary tests. I've added a quick and dirty integration test that succeeds - it synthesizes some text and saves to mp3. Listening to the …

feat: initial TTS support

---

messages.go

Calling the `CreateMessage` method currently fails with the following error message: `You must provide the 'OpenAI-Beta' header to access the Assistants API. Please try again by setting the header 'OpenAI-Beta: assistants=v1'.`
I've updated the `CreateMessage` call in `messages.go` to include the `withBetaAssistantV1()` request option.
**Tests**
It was unclear how to update the tests as I didn't see a way to test the header was set.  I have tested that the call succeeds in my application now.

fix: add beta assistant header to CreateMessage call

---

client_test.go
files.go
files_api_test.go
files_test.go

`CreateFile` currently requires a "local" file which it reads from the filesystem and uploads.  For various reasons, we require uploading bytes directly rather than relying on local filesystem.
Add `CreateFileBytes` which takes a `FileBytesRequest` that allows directly passing a `[]byte`.  This reuses the exsting `CreateFormFileReader` passing a `*bytes.Reader` directly.
**Tests**
Added a test case to `files_api_test.go`.   Also validated that it works in a separate app.

feat: support direct bytes for file upload

---

run.go

add RunStepList response args
```
type RunStepList struct {
...
FirstID string `json:"first_id"`
LastID  string `json:"last_id"`
HasMore bool   `json:"has_more"`
...
}
```
ref: …

feat(runapi):  add RunStepList response args 

---

assistant.go

The [API docs](https://platform.openai.com/docs/api-reference/assistants/object) define the `Assistant` object as:
```json
{
"id": "asst_abc123",
"object": "assistant",
"created_at": 1698984975,
"name": "Math Tutor",
"description": null,
"model": "gpt-4",
"instructions": "You are a personal math tutor. When asked a question, write and run Python code to answer the question.",
"tools": [
{
"type": "code_interpreter"
}
],
"file_ids": [],
"metadata": {}
}
```
However the `Assistant` type in this package does not have the following properties:
- `file_ids`
- `metadata`
Add them to the `Assistant` type.
No issues related to this, I noticed it when wanting to validate the metadata of an existing Assistant.

Add Assistant FileIDs and Metadata

---

files.go

- When uploading a `File`, you need to define a `.Purpose`
- Currently this is a `string` that is passed to the `FileRequest` type
- It would be nicer to have these as constants
> See: https://platform.openai.com/docs/api-reference/files
Add a constant for each supported purpose as defined in the OpenAI API.
No tests needed.
Not related to an issue, just something I saw when using the new Assistants API.

Add File purposes as constants

---

run.go

Querying run steps will create marshalling error like: 
`json: cannot unmarshal array into Go struct field StepDetails.data.step_details.tool_calls of type openai.StepDetailsToolCalls`
The [official …

Updates the tool call struct

---

messages.go
messages_test.go

Describe the change
Missing pagination parameters for new assistants list API
Describe your solution
Add missing parameters
Tests
Verified against endpoint
Additional context
```
curl https://api.openai.com/v1/threads/thread_abc123/messages \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $OPENAI_API_KEY" \
-H "OpenAI-Beta: assistants=v1"
{
"object": "list",
"data": [],
"first_id": "msg_abc123",
"last_id": "msg_abc456",
"has_more": false
}
```
Issue: resolves #583 
Similar PR: https://github.com/sashabaranov/go-openai/pull/571

Add missing response fields for pagination

---

speech.go

There is an additional text-to-speech model called "canary-tts", which is not advertised on OpenAI's API documentation page, nevertheless it appears among the allowed models, and it seems to work with exactly the same voices as the main tts-1 models in exactly the same way.
The only important difference is that it is currently not rate limited as aggressively as the tts-1 models, which may be useful for those on the free tier.
It's entirely possible that the mere existence of this model is a mistake on OpenAI's part, but as long as it is available, we might as well use it.
The commit also fixes a typo in one of the existing constants. This is technically a breaking change, but it seemed like the proper thing to fix it.

Add canary-tts to speech models

---

examples/completion-with-tool/main.go

Add a completion-with-tool example showing how to correctly utilize the function calling capability of GPT4
This is based on the existing completion example and uses the same get_current_weather() python function that the OpenAI documentation includes.
**Tests**
Manually run the new example.
As a user of this go SDK it was not immediately intuitive to me how to correctly utilize the function calling capability of GPT4 (https://platform.openai.com/docs/guides/function-calling). While the aformentioned link provides a helpful example written in python, I initially tripped over how to correctly translate the specification of function arguments when using this go SDK.

Add completion-with-tool example

---

chat.go

OpenAI finally released log probabilities for chat completions. This PR implements the required changes to be able to request log probabilities in chat completion requests and receive them in the chat completion response.
https://platform.openai.com/docs/api-reference/chat/object
Added `logprobs` and `top_logprobs` in the chat completion request and response.
**Tests**
Manually tested by making chat completions
**Issues**
Closes #626

Log probabilities for chat completion output tokens

---

embeddings.go
embeddings_test.go

This gives the user the ability to pass in models for embeddings that are not already defined in the library. Also more closely matches how the completions API works.
Addresses the issue described in #602 essentially that forcing embedding model to be represented as an int is awkward.
The integer representation is never used by openai, only the string https://platform.openai.com/docs/api-reference/embeddings
Gets rid of the extra layer of indirection and uses the string value directly.
**Tests**
This mostly ended up deleting code, and so deleted the associated test as well.
Add any other context or screenshots or logs about your pull request here. If the pull request relates to …

[BREAKING_CHANGES] convert EmbeddingModel to string type

---

image.go

fix #594 APITypeAzure dall-e-3 model url
fix #594 APITypeAzure dall-e-3 model url
Issue: #594

fixed #594

---

embeddings.go
embeddings_test.go

A [recent pull request](https://github.com/sashabaranov/go-openai/pull/629) broke support for the Azure OpenAI embeddings endpoint by [passing a variable of type `EmbeddingModel` to `client.fullURL`](https://github.com/sashabaranov/go-openai/pull/629/files#diff-0fdd78c64708f1e3c576725363d6d7accb8b43590810436765198e7a5522770fR231). This breaks the [Azure deployment name lookup](https://github.com/sashabaranov/go-openai/blob/09f6920ad04666f65dd86ed542e5ebf8bffc93a8/client.go#L223-L229).
This pull request fixes Azure embeddings support by casting the type to `string`.
**Tests**
Added tests for generating Azure embeddings 
Note: I'm not a great Go programmer. If there's a better way to do this I'm all ears!

Fix Azure embeddings model detection by passing string to `fullURL`

---

client.go
client_test.go

The audio api passes `audioTextResponse` to `sendRequest`,
```go
if request.HasJSONResponse() {
err = c.sendRequest(req, &response)
} else {
var textResponse audioTextResponse
err = c.sendRequest(req, &textResponse)
response = textResponse.ToAudioResponse()
}
```
but it cannot be asserted as `*string` type, lead to decoding failure.
```go
func decodeResponse(body io.Reader, v any) error {
if v == nil {
return nil
}
if result, ok := v.(*string); ok {
return decodeString(body, result)
}
return json.NewDecoder(body).Decode(v)
}
```
Fix this problem.

fix(audio): fix audioTextResponse decode

---

embeddings.go

Add new struct field `dimensions`  that support for shortening embeddings. Release in January 25, 2024
* [New embedding models and API updates](https://openai.com/blog/new-embedding-models-and-api-updates)
* [Embedding API Reference](https://platform.openai.com/docs/api-reference/embeddings)
Add new struct filed
**Tests**
manual

Add new struct filed dimensions for embedding API

---

run.go

RunStatusCancelled is omitted.
https://platform.openai.com/docs/assistants/how-it-works/run-lifecycle

Fix: Add RunStatusCancelled

---

run.go

Feat: Add assistant usage

---

client.go
embeddings_test.go
files_api_test.go
image_test.go
messages.go
models_test.go
run.go
speech.go
stream_test.go

Sometimes I get answer for all request:
`{
"error": {
"message": "Unsupported content type: 'application/json; charset=utf-8'. This API method only accepts 'application/json' requests, but you specified the header 'Content-Type: application/json; charset=utf-8'. Please try again with a supported content type.",
"type": "invalid_request_error",
"param": null,
"code": "unsupported_content_type"
}
}`
It depends of account.
There is no such header "charset:utf-8" in the official library on python

Content-type fix

---

run.go

AdditionalInstructions is an optional string field used to append additional instructions at the end of the instructions for the run. This is useful for modifying the behavior on a per-run basis without overriding other instructions.
https://platform.openai.com/docs/api-reference/runs/createRun#runs-createrun-additional_instructions

Add RunRequest field AdditionalInstructions

---

client.go

Currently I am hosting my LiteLLM proxy with no Authorization and trying to connect with go-openai like this:
```
config := openai.DefaultConfig("")
config.BaseURL = "https://my-service/v1"
aiClient := openai.NewClientWithConfig(config)
```
It shows an error because I am passing empty token but it still appends Bearer header
```
2024/02/12 12:51:54 Failed to create chat stream: error, status code: 401, message: Authentication Error,
^Csignal: interrupt
```
While not passing any authorization header works for my proxy server

Update client.go - allow to skip Authorization header

---

chat.go
examples/completion-with-tool/main.go

modify Tool's Function to pointer
https://community.openai.com/t/retrievals-tool-not-permitted/628664
using pointer，Avoiding 'null' values for the 'function' field when serializing to JSON
Issue: #663

fix:fix open ai original validation. modify Tool's Function to pointer

---

assistant_test.go
client.go

Assistants API is broken for Azure OpenAI implementation returning a 404 error
Expected URL = https://YOUR_RESOURCE_NAME.openai.azure.com/openai/assistants?api-version=2024-02-15-preview
Current URL = https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/UNKNOWN/assistants?api-version=2024-02-15-preview
Link to Microsoft docs: https://github.com/MicrosoftDocs/azure-docs/blob/bb63f74fabd8a70267e1ab2960773f706c8c50c3/articles/ai-services/openai/assistants-reference.md
Fix removes /deployments/UNKNOWN/ by using same approach for /models API
Added unit tests for Azure Assistants APi

Fix for broken Azure Assistants url

---

moderation.go
moderation_test.go

PR #662 has broken the json decoding of moderation responses by changing the type of score values from float32 to bool. This commit fixes that problem.

fix: repair json decoding of moderation response

---

speech.go

Added "wav" and "pcm" audio formats as per OpenAI API documentation for createSpeech endpoint.  Ref: https://platform.openai.com/docs/api-reference/audio/createSpeech 
Supported formats are mp3, opus, aac, flac, wav, and pcm.
**OpenAI documentation link**
[ Relevant API doc from https://platform.openai.com/docs/api-reference
](https://platform.openai.com/docs/api-reference/audio/createSpeech)

Added 'wav' and 'pcm' Audio Formats

---

stream_reader.go

This commit updates the Close() method of the streamReader struct to return an error. This allows callers to handle any errors that occur when closing the stream.

Update streamReader Close() method to return error

---

assistant.go
assistant_test.go

This resolves https://github.com/sashabaranov/go-openai/issues/684 
both reverts the changes in https://github.com/sashabaranov/go-openai/pull/669
and modifies the code to actually match the intention of the https://github.com/sashabaranov/go-openai/pull/669
Currently the SDK does not match the API and requires all of the existing tools to be provided in every request to avoid an API error or deleting all of the tools. Please see the linked issue for repro steps and use cases including step by step cURL requests to demonstrate the existing functionality of the API
As specified in the inline documentation
A custom marshaller was required here to handle the various use cases of the API request with respect to GO-isms and to avoid breaking changes:
If Tools is nil (or undefined), the field …

Fix broken implementation AssistantModify implementation

---

client.go
files.go
speech.go

Add response header to `CreateSpeech` and `GetFileContent`.
Replace `io.ReadCloser` with `RawResponse`, which contains an `io.ReadCloser` and a `httpHeader`. The `RawResponse` can be treated as `io.ReadCloser` therefore keeping backwards compatibility.

feat: get header from sendRequestRaw

---

.github/workflows/close-inactive-issues.yml
.github/workflows/pr.yml

This PR bumps GitHub workflow actions to their latest versions, thus avoiding deprecation warnings as e.g. seen [here](https://github.com/sashabaranov/go-openai/actions/runs/8643918363).

Bump GitHub workflow actions to latest versions

---

run.go

.**Describe the change**
OpenAI quietly released a major upgrade of their Assistant's API which gives us vital cost management functionality with easy to use parameters 
[(https://platform.openai.com/docs/api-reference/runs)](https://platform.openai.com/docs/api-reference/runs)
Not much to mention, it simply adds the new parameters to the object
**Tests**
as these are just extra fields in the request and response object, it cannot really be tested with unit tests
I purposely skipped some of the other new fields such as 
Stream, which requires more infrastructure and should be it's own PR to define a properly abstracted streaming solution
I also skipped tool_choice and response_format, both because the …

[New_Features] Adds recently added Assistant cost saving parameters

---

chat_stream.go

Adding field for `prompt_filter_results` which is in the open content filters to assess the content of the user input. Current implementation in go-openai will only return content filter information on the model output using `ChatCompletionStreamResponse`. This is for AzureOpenAI spec.
Relevant API doc: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/content-filter
[See Bottom under Annotations]
Change struct

Add prompt filter results to content filters

---

assistant.go
client.go
config.go
messages.go
run.go
thread.go

OpenAI released assistants v2, however the code currently hardcodes `v1` in every assistant and thread method.
https://platform.openai.com/docs/assistants/migration
I've added an `AssistantVersion` parameter in the client config, which defaults to `v1`, so there will be no breaking change for anyone.
Users will be able to use `v2` and any future versions by passing the version in the client config.
**Tests**
I've been using this in our fork of `go-openai`.
Issue: #717

Remove hardcoded assistants version

---

image_api_test.go

Just a minor typo in a copy-pasta comment that I noticed; `imagess` to `images`.

Fixup minor copy/pasta comment typo

---

audio.go
audio_api_test.go
audio_test.go

Add support for word-level audio transcription timestamp granularity.
- [timestamp_granularities[]](https://platform.openai.com/docs/api-reference/audio/createTranscription#audio-createtranscription-timestamp_granularities)
- [words](https://platform.openai.com/docs/api-reference/audio/verbose-json-object#audio/verbose-json-object-words)
Added `AudioRequest.TimestampGranularities` and `AudioResponse.Words` fields.
**Tests**
Filled `AudioRequest.TimestampGranularities` field in the existing tests' audio requests.
- Related to two-months-abandoned #673, self-closed #680, and self-closed #674.
- Also removed some obsolete comments on `AudioRequest` fields.

Add support for word-level audio transcription timestamp granularity

---

chat.go
chat_stream.go
chat_stream_test.go

support stream_options
Provide a relevant API doc from https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options

feat: support stream_options

---

completion.go

This PR introduces two new enums for OpenAI's new model release: `GPT4-o`
https://platform.openai.com/docs/models/gpt-4o

enhancement: Add new GPT4-o and alias to completion enums

---

client.go

Update client.go to get response header whether there is an error or not. Because 429 Too Many Requests error response has "Retry-After" header.
Please provide a clear and concise description of the changes you're proposing. Explain what problem it solves or …

Update client.go to get response header whether there is an error or not

---

run.go

This PR adds the missing `incomplete` run status to the code, which is defined in the OpenAI documentation but was not present in the codebase.
Additionally, I corrected discrepancies between the documentation and the code for the explanations of MaxPromptTokens and MaxCompletionTokens.
[OpenAI Documentation on Run Lifecycle](https://platform.openai.com/docs/assistants/how-it-works/run-lifecycle)

Add incomplete run status

---

thread.go

Support Tool Resources properties for Threads.
- https://platform.openai.com/docs/api-reference/threads/createThread
- https://platform.openai.com/docs/api-reference/threads/modifyThread
- https://platform.openai.com/docs/api-reference/threads/object
Describe how your changes address the problem or how they add the feature. This should include a brief description of your approach and any new libraries or dependencies you're using.
**Tests**
I've manually tested the functionality when using the library in the project I'm working on.
Resolves https://github.com/sashabaranov/go-openai/issues/759

Support Tool Resources properties for Threads

---

assistant.go
config.go
vector_store.go
vector_store_test.go

Just want to finish this feature, thanks
implement vector strore api (including vector file + file batch)
https://platform.openai.com/docs/api-reference/vector-stores

feat: provide vector store

---

batch.go

Removes `errors.Join` to make the library backwards-compatible with go 1.18 and 1.19
#774

fix: remove errors.Join

---

speech.go
speech_test.go

this pull request removes the client-side logic to verify a valid speech and voice model.
the motivation is to support custom models on openai compatible backends
thanks for considering

Allow custom Voice and Speech Models

---

chat.go
chat_test.go

Openai has by default a `parallel_tool_calls` set to true, which allows the llm to make multiple tool calls in one response.
This can be opted out of with setting it to false, and ensures the llm only responds with one tool call at a time.
https://platform.openai.com/docs/guides/function-calling/parallel-function-calling
We only need to set the field to false, and true for being certain it is true, we can not just use a `bool` type.
As that would require a custom marshaller for not including it when not set.
I think a `*bool` works oke here, it is a bit annoying to set a `*bool` value. Which is why the helper functions have been given: `ParallelOptionFalse()` and `ParallelOptionTrue()`.
Intended use: …

feat: ParallelToolCalls to ChatCompletionRequest with helper functions

---

client.go

fix: Azure openai parameter splicing error bug 

---

thread.go

ThreadMessage has deprecated fields, and new fields are missing, so requests with files cannot be made.
https://platform.openai.com/docs/api-reference/threads/createThread
Updated ThreadMessage based on OpenAI docs.

fix: Updated ThreadMessage struct with latest fields based on OpenAI docs

---

fine_tuning_job.go
fine_tuning_job_test.go

Adds `learning_rate_multiplier` and `batch_size` parameters.
Supported by both OpenAI and Azure, see:
* https://platform.openai.com/docs/api-reference/fine-tuning/create
* https://learn.microsoft.com/en-us/rest/api/azureopenai/fine-tuning/create?view=rest-azureopenai-2024-03-01-preview&tabs=HTTP#finetuninghyperparameters

add finetuning hyperparams

---

assistant.go

This update introduces three new optional parameters to the `AssistantRequest` struct: `ResponseFormat`, `Temperature`, and `TopP`. These parameters provide additional control over the output format and sampling behavior of the OpenAI assistant, enhancing its flexibility and usability.
For detailed information about these parameters, please refer to the OpenAI API documentation: [OpenAI API Reference](https://platform.openai.com/docs/api-reference/assistants/object)
The solution involves extending the `AssistantRequest` struct to include the following fields:
- `ResponseFormat any`: Specifies the format that the model must output. Example: setting this to `{ "type": "json_object" }` ensures the model generates valid JSON. but it can also be a string format for 'auto'
- `Temperature …

Add New Optional Parameters to `AssistantRequest` Struct

---

batch.go

fix: cannot unmarshal array into Go struct field .errors.data

---

api_integration_test.go
chat.go
jsonschema/json.go

Support Structured Outputs 
https://platform.openai.com/docs/guides/structured-outputs/introduction

feat: Support Structured Outputs

---

chat.go

This morning's PR #813 makes it impossible to do ChatCompletionRequest that doesn't supply a json schema.
I followed the suggestion in #818, changing the JSONSchema attached to a request format object to a pointer type, so that the JSON marshaler can properly exclude it when not provided.
**Tests**
I ran the go tests.  (did you guys know you have a bunch of broken tests in the repo?)
All tests pass except for the ones in the jsonschema directory.  Those tests were broken both before and after my changes.
I updated my own software to use my fork, and everything works.
Issue: #818

Make reponse format JSONSchema optional

---

.github/workflows/integration-tests.yml
api_integration_test.go

Unbreak the integration tests syntax.
Follow-up to https://github.com/sashabaranov/go-openai/pull/820.

Run integration tests for PRs

---

api_integration_test.go
chat.go
chat_test.go

Allows `strict: true` to be passed to OpenAI within a function's definition, triggering OpenAI's new [structured outputs](https://openai.com/index/introducing-structured-outputs-in-the-api/) setup to ensure the function's schema is strictly adhered to.
https://openai.com/index/introducing-structured-outputs-in-the-api/
Add `Strict` to the properties of `FunctionDefinition`. Only serialise it in the JSON if its value is `true` (to avoid wasting tokens).
**Tests**
Added a test.
None

Allow structured outputs via function calling

---

client_test.go
fine_tunes.go
messages.go
messages_test.go

- support Delete Message API
- No breaking changes
relevant API doc from https://platform.openai.com/docs/api-reference/messages/deleteMessage
- fix lint

feat: Support Delete Message API

---

config.go

**Description**
It would be great to be able to wrap `http.Client` for logging, having metrics, timings, alerting etc.
**Solution**
Just use interface instead of concrete type.
**Detailed example**
For instance, I would like to be able to do something like that:
```go
type httpClientIf interface {
Do(req *http.Request) (*http.Response, error)
}
type debugClient struct {
next httpClientIf
}
func (dc *debugClient) Do(req *http.Request) (*http.Response, error) {
t := time.Now()
r, err := dc.next.Do(req)
fmt.Printf("%s %s -> %v -> %d\n", r.Request.Method, r.Request.URL.String(), time.Since(t), r.StatusCode)
return r, err
}
...
client := openai.NewClientWithConfig(openai.ClientConfig{
HTTPClient: &debugClient{next: http.DefaultClient}, // <--- wrapping, thanks to interfaces
})
```
To see …

Support http client middlewareing

---

completion.go

- New Dynamic model that always points to the latest GPT4o model.
OpenAi documentation for this can be found here: https://platform.openai.com/docs/models/gpt-4o

Dynamic model

---

jsonschema/validate.go
jsonschema/validate_test.go

Fix the jsonschema validation failed failure on the integer field.
Follow the #837 instruction. Because go unmarshalls all numbers as float64, we should check the value is an integer.
**Tests**
Add `jsonschema.Integer` cases, include a success and a failed case.
Add any other context or screenshots or logs about your pull request here. If the pull request relates to an open issue, please link to it.
Issue: #837

fix: jsonschema integer validation

---

chat.go
chat_stream.go
chat_stream_test.go
chat_test.go
completion.go

For new `o1 series models` attribute `max_tokens` not working. In documentation this field marks deprecated.
OpenAi introduced new attribute  `max_completion_tokens`.
```
To manage costs with the o1 series models, you can limit the total number of tokens the model generates (including both reasoning and completion tokens) by using the [max_completion_tokens](https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_completion_tokens) parameter.
In previous models, the max_tokens parameter controlled both the number of tokens generated and the number of tokens visible to the user, which were always equal. However, with the o1 series, the total tokens generated can exceed the number of visible tokens due to the internal reasoning tokens.
Because some …
```

add max_completions_tokens for o1 series models

---

run.go

By default, `parallel_tool_calls` is set to true, which allows the llm to make multiple tool calls in one response. This can be opted out of with setting it to false, and ensures the llm only responds with one tool call at a time.
https://platform.openai.com/docs/api-reference/runs/createRun#runs-createrun-parallel_tool_calls
This PR added the same change as #787 , an `any`  field `ParallelToolCalls`.
**Tests**
No new tests added.

feat: add ParallelToolCalls to RunRequest

---

client_test.go
messages.go
messages_test.go

Filter messages by the run ID that generated them.
Please provide a clear and concise description of the changes you're proposing. Explain what problem it solves or what feature it adds.
Provide a relevant API doc from …

Filter messages by the run ID that generated them. (run_id string Optional) 

---

client.go
client_test.go
error.go
files_api_test.go

Optimize Client Error Return

---

chat.go

The json tag is incorrect, and results in an error from the API when using the o1 model.  
I didn't modify the struct field name to maintain compatibility if anyone else had started using it, but it wouldn't work for them either.

Fix max_completion_tokens

---

run.go

Sorry about that, my previous PR #847 didn't add this field into to the correct struct, it should be added to `RunRequest`, but not `Run`.
[Provide a relevant API doc from https://platform.openai.com/docs/api-reference](https://platform.openai.com/docs/api-reference/runs/createRun#runs-createrun-parallel_tool_calls)

fix: ParallelToolCalls should be added to RunRequest

---

chat.go
chat_test.go
completion.go

Currently API calls to o1 models are broken due to a typo in the json tag of `ChatCompletionRequest`
This PR corrects the spelling of `MaxCompletionsTokens` to `MaxCompletionTokens` and also fixes the json tag `max_completion_tokens`. 
There already exists a [similar PR](https://github.com/sashabaranov/go-openai/pull/860) but it doesn't fix all occurrences of the typo.

fix MaxCompletionTokens typo

---

chat.go

Adding field for prompt_filter_results which is in the open content filters to assess the content of the user input. Current implementation in go-openai will only return content filter information on the model output using ChatCompletionResponse. This is for AzureOpenAI spec.
Adding field for content_filter_results which is in the open content filters to assess the content of the user input. Current implementation in go-openai will only return content filter information on the model output using ChatCompletionChoice. This is for AzureOpenAI spec.
Adding field for jailbreak which is in a content filter. Current implementation in go-openai will only return content filter information on the error output using InnerError.ContentFilterResults. This is for AzureOpenAI spec.
Provide OpenAI …

add jailbreak filter result, add ContentFilterResults on output

---

common.go
completion.go

- `store` in request: this param allows you to opt a completion request in to being stored, for use in distillations and evals.
- `usage.completion_tokens_details.audio_tokens` in response: tracking audio tokens generated
- `usage.prompt_tokens_details` in response: tracking tokens used in the prompt
https://platform.openai.com/docs/api-reference/chat/create#chat-create-store
https://platform.openai.com/docs/api-reference/chat/object#chat/object-usage
Currently it's not possible to opt a completion request in to being stored using go-openai, blocking usage of distillations and evals.
It's also not possible to track usage of audio tokens, nor prompt caching.
**Tests**
These are optional new params, so …

Completion API: add new params

---

client.go
error.go

When the inference engine returns an error response that is not of type openai.ErrorResponse, a decode error occurs, leading to the loss of the original error message from the inference engine. To address this issue, this PR implements a change in the go-openai client that ensures the error from the inference engine is included in the openai.RequestError response. This enhancement preserves the original error information, providing clearer insights into the underlying issues.
Introduced a new field called Body of type []byte in the openai.RequestError struct. This field stores the byte slice of the error response body received from the inference engine when the error response does not conform to the openai.ErrorResponse type. This …

Return response body as byte slice for RequestError type

---

chat.go
completion.go

The `store` parameter recently introduced by OpenAI has been added to `CompletionRequest` already in #870 ; it is here added to `ChatCompletionRequest`, and the related `metadata` parameter added to both.
https://platform.openai.com/docs/api-reference/chat/create#chat-create-store
https://platform.openai.com/docs/api-reference/chat/create#chat-create-metadata
Simply adds new fields to the API call objects.
**Tests**
No new tests added.
(Partly addresses) Issue: #872

Completion API: add Store and Metadata parameters

---

client.go
client_test.go
error.go

Since the original error response is included in the body field of openai.RequestError, even when the response is not in JSON format, it would be more appropriate to return openai.RequestError directly, rather than returning an errorString. This approach ensures that the original error details are preserved within the body field.
Removed the condition that checked if the response was in a non-JSON format and returned an errorString with the original error response. Now, the original error response will be directly included in the body field of openai.RequestError.

Handling for non-json response

---

chat_stream.go
chat_stream_test.go

Like #844, In ChatCompletionStream.delta the refusal and logprobs field is missing
[Provide a relevant API doc from https://platform.openai.com/docs/api-reference](https://platform.openai.com/docs/api-reference/chat/streaming#chat/streaming-choices)
Add Refusal and Logprobs Fields
**Tests**
n/a
n/a

add chatcompletion stream delta refusal and logprobs

---

vector_store.go

This change adds pagniation properties for listing Vector Store Files.  A vector store can handle up to 10,000 files at the time of this PR and a max of 100 files can be returned per request.
It's not specifically outlined in the documentation, however, the example response has these fields listed.  
https://platform.openai.com/docs/api-reference/vector-stores-files/listFiles
Added the missing properties that are returned from the API request.

Added Vector Store File List properties that allow for pagination

---

messages.go
thread.go

Add Attachments field in MessageRequest struct so we can attach file to thread message and can refer the file in chat content.
https://platform.openai.com/docs/api-reference/messages/createMessage
Adding Attachments Field and tools type const in message.go
**Tests**
using unit test and example app
-
Issue: -

Support Attachments in MessageRequest

---

.golangci.yml
client_test.go

Latest version of golangci-lint is used in github workflows to check for lint errors. The [recent release](https://github.com/golangci/golangci-lint/releases/tag/v1.62.0) of golangci-lint introduced additional linting rules, which surfaced a new [lint error](https://github.com/sashabaranov/go-openai/actions/runs/11833389300/job/32971951797#step:5:25) in client_test.go file. Also linter execinquery is deprecated and linter gomnd is replaced by mnd [more info](https://github.com/golangci/golangci-lint/pull/5110)
This PR addresses and resolves that newly reported lint error and removes the deprecated linters.
PR adds a type assertion to check if the recovered panic value (r) is a string before comparing it to the expected panic message …

Updated client_test to solve lint error

---

batch_test.go
embeddings.go

Added `omitempty` json tag for the `User` field in the `EmbeddingRequest` struct. This field is optional in embedding requests as per OpenAI spec.
Issue: If you don't specify any user in the embedding request, the current spec sends the user as an empty string for which embedding models throw errors.
https://platform.openai.com/docs/api-reference/embeddings/create#embeddings-create-user
Added `omitempty` json tag for the `User` field in the `EmbeddingRequest` struct. This will make the `User` field optional as per openai embeddings spec.
**Tests**
Tested the above change by sending embeddings requests to the embeddings model with following payload:
```
curl -k -X 'POST' '/embeddings' \
-H 'accept: …
```

Make user field optional in embedding request

---

completion.go

feat: add gpt-4o-2024-11-20 model

---

stream_reader.go
stream_reader_test.go

To address the need for reading raw stream lines or customizing stream responses, we have introduced a RecvRaw method to the streamReader. This enhancement allows for more flexible and direct interaction with stream data.
Fixes #887, #889.

feat: add RecvRaw

---

.golangci.yml
audio_api_test.go
audio_test.go
image_api_test.go
internal/form_builder_test.go
internal/test/helpers.go
openai_test.go
speech_test.go

The PR refactors tests that contain `os.MkdirTemp` and `os.Remove` with [`T.TempDir`](https://pkg.go.dev/testing#T.TempDir). That allows to remove 50 lines of test code without harming readability.
Also, enables [`usetesting`](https://golangci-lint.run/usage/linters/#usetesting) to automatically detect this in the future.
The PR replaces usages of `CreateTestDirectory` with `t.TempDir()`. It's not needed to call `os.Remove` anymore.
> TempDir returns a temporary directory for the test to use. The directory is automatically removed when the test and all its subtests complete.

Simplify tests with T.TempDir

---

chat.go
completion.go
openai_test.go

The `reasoning_effort` controls the amount of reasoning done by OpenAI's new series of Reasoning models
https://platform.openai.com/docs/api-reference/chat/create#chat-create-reasoning_effort
Adds the optional parameter
Also added the new `o1` models
**Tests**
Tested locally with the `o1` model

Chat Completion API: add ReasoningEffort and new o1 models

---

chat.go
chat_test.go
openai_test.go

According to the OpenAI API spec, the content field of ChatCompletionMessage should be nullable. Right now when we try to marshal the struct with empty string, we get `"content": ""`, but ideally, the content key should exist if that field is empty
https://platform.openai.com/docs/api-reference/chat/object
Under: choices -> message -> content
We can fix this my adding an omitempty json tag to the "content" field in the "ChatCompletionMessage" struct
**Tests**
Tested this by sending a completion request with empty content field to a Nvidia NIM Inference Server

Make "Content" field in "ChatCompletionMessage" omitempty

---

chat.go
chat_stream.go
chat_stream_test.go
chat_test.go
completion.go
reasoning_validator.go

- Add support for the o3 mini set of models, including tests that match the constraints in OpenAI's API docs (https://platform.openai.com/docs/models#o3-mini).

Add support for O3-mini

---

.github/workflows/pr.yml
chat_test.go
reasoning_validator.go

In the latest openai o1 release o1-2024-12-17, Function calling is supported, and I test that system roles can be passed
see: https://openai.com/index/o1-and-new-tools-for-developers/

fix: remove validateO1Specific

---

client.go
client_test.go
config.go
config_test.go

Add support for Anthropic models.
**Provide documentation link**
Anthropic API requests require a custom header "anthropic-version". More details [here](https://docs.anthropic.com/en/api/versioning)
Added new APITypeAnthropic with APIVersion = "2023-06-01" and baseURL of "https://api.anthropic.com/v1"
**Tests**
Checking correct APIVersion and default baseURL.
Currently, trying to override the default config with Anthropic values, fails with a 404 not found error (because there's no request header "anthropic-version":"2023-06-01").

feat: add Anthropic API support with custom version header

---

.github/workflows/pr.yml
jsonschema/json.go
jsonschema/json_test.go

> A similar PR may already be submitted!
> Please search among the [Pull request](https://github.com/sashabaranov/go-openai/pulls) before creating one.
There is another issue, #912. It seems to have been abandoned.
When creating a JSON schema from a `struct`, a new tag `enum` can be used to see the `Enum` field.
For example,
```go
type Car struct {
Color string `json:"color" enum:"red,green,blue"`
}
```
This will see the `Enum` on the field definition would be `Enum = []string{"red","green","blue"}`.
This is implementation is being [used](https://github.com/jtarchie/outrageous/blob/519dce0dc981b0bf37e41890dc49b6ec6859970e/assert/assert.go#L24).
Provide a relevant API doc from https://platform.openai.com/docs/api-reference …

add enum tag to jsonschema

---

speech.go

This adds the new OpenAI TTS model, includes a new instructions field, and adds missing speech voices.
https://platform.openai.com/docs/api-reference/audio
- Add `TTSModelGPT4oMini` to `SpeechModel` type
- Adds missing voices to `SpeechVoice` type
- Added an optional `instructions` field to the `CreateSpeechRequest` object, specific to the `gpt-4o-mini-tts` model.
**Tests**
No test changes were required. The `SpeechModel` and `SpeechVoice` types were already defined, and the `instructions` field is omitted when empty.

feat: Add missing TTS models and voices

---

stream_reader.go

This is an alternative to another PR https://github.com/sashabaranov/go-openai/pull/932
Instead of compare header string, this PR use regex pattern to match and replace the header. It seems a more clear way to implement it.

Adapt different stream data prefix, with or without space

---

chat_stream_test.go
completion.go
completion_test.go
models_test.go
reasoning_validator.go

- This adds supports, and tests, for the o3 and o4-mini class of models
https://platform.openai.com/docs/models/o4-mini
https://platform.openai.com/docs/models/o3

Add support for `o4-mini` and `o3`

---

completion.go

The legacy completion API supports [a `stream_options` object when `stream` is set to true](https://platform.openai.com/docs/api-reference/completions/create#completions-create-stream_options). This adds a StreamOptions property to the CompletionRequest struct to support this setting.
https://platform.openai.com/docs/api-reference/completions/create#completions-create-stream_options
This adds a `StreamOptions` property (marshaled as `stream_options`) to the `CompletionRequest` struct to expose the setting. This matches the `ChatCompletionRequest` property.

Add CompletionRequest.StreamOptions

---

.golangci.yml

This PR removes redundant `typecheck` from the `linters.enable` list.
`typecheck` is not a linter and it doesn't perform any analysis. It's just a way to identify, parse, and display compiling errors and some linter errors.
More info:
- https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors
- https://golangci-lint.run/welcome/faq/#why-is-it-not-possible-to-skipignore-typecheck-errors

Remove redundant typecheck linter

---

chat.go
common.go

Adding the prediction field which allows for using [Predicted Outputs](https://platform.openai.com/docs/guides/predicted-outputs).
https://platform.openai.com/docs/api-reference/chat/create#chat-create-prediction
Adds the optional parameter and modifies the response to include how many prediction tokens it used
**Tests**
Briefly describe how you have tested these changes. If possible — please add integration tests.
Tested locally and verified that I received predicted tokens accepted in the response
Issue: #954

Add Prediction field

---

completion.go

Someone typo'd the O4 mini model name in #968. Fixed it in this PR.
N/A
Self-explanatory
**Tests**
Tests didn't need to be updated as this was a variable naming change only. The underlying model name was correct.
[See this issue](https://github.com/sashabaranov/go-openai/issues/982)

Fix: Corrected typo in o4-mini model name and fixed endpoint map

---

audio_test.go
config_test.go

- **add tests for config**
- **add audio tests**

Improve unit test coverage

---

.github/workflows/pr.yml
.golangci.yml

Upgrade golangci-lint to 2.1.5

---

README.md
examples/images/main.go
image.go

This PR adds support for the new `gpt-image-1` model from OpenAI, along with several missing constants and optional fields related to image generation.
- https://platform.openai.com/docs/guides/image-generation?image-generation-model=gpt-image-1
- https://platform.openai.com/docs/api-reference/images
- Added constant for the new `gpt-image-1` model.
- Included image sizes specific to the model: 1536x1024 (landscape), 1024x1536 (portrait).
- Added quality levels: low, medium, high.
- Added background options: transparent, opaque.
- Added moderation level: low.
- Added output formats: png, jpeg, webp.
- Updated the Request and Response structs to include optional fields from the OpenAI API response that …

feat: add support for image generation using `gpt-image-1`

---

internal/error_accumulator_test.go
internal/form_builder.go
internal/form_builder_test.go
internal/marshaller_test.go
internal/unmarshaler_test.go

enhance error accumulator and form builder tests, add marshaller tests
added some edge case tests to improve test coverage
Issue: #997

test: enhance error accumulator and form builder tests, add marshaller tests

---

chat.go

This adds support for specifying the Service Tier in a chat completion request.
https://platform.openai.com/docs/api-reference/chat/create#chat-create-service_tier
- Added `service_tier` to the chat completion request and response
- Added consts for the possible `service_tier` values, based on the [documentation](https://platform.openai.com/docs/api-reference/chat/create#chat-create-service_tier)
- The `priority` value is only available to enterprise customers and isn't in the API Reference. It is documented here: https://openai.com/api-priority-processing/
**Tests**
- Manually tested calling the chat completion endpoint with the `service_tier` to `flex`.
- Manually regression tested calling the …

Add support for Chat Completion Service Tier

---

chat.go

Adds guided_choice param support to chat completions
[Structured output vLLM support](https://docs.vllm.ai/en/latest/features/structured_outputs.html#online-serving-openai-api)
```
curl --request post \
--url http://localhost:8000/v1/chat/completions \
--header 'Content-Type: application/json' \
--data '{
"model": "llama3-3b",
"messages": [
{
"role": "user",
"content": "Classify this sentiment: vLLM is great!"
}
],
"guided_choice": [
"negative",
"positive"
]
}'
```

Add GuidedChoice to ChatCompletionRequest

---

chat.go

This commit shortens a long comment in chat.go to pass the golangci-lint checks.

fix(chat): shorten comment to pass linter

---

chat.go

Verbosity - Constrains the verbosity of the model's response. Lower values will result in more concise responses, while higher values will result in more verbose responses. Currently supported values are low, medium, and high.
OpenAI Docs - https://platform.openai.com/docs/api-reference/chat/create#chat_create-verbosity
✅ All existing tests pass

Add Verbosity parameter to Chat Completion Request
