sashabaranov/go-openai

- api_test.go
- embeddings.go
Adds ability to create embeddings.
See more:
https://beta.openai.com/docs/guides/embeddings/what-are-embeddings
https://beta.openai.com/docs/api-reference/embeddings/create
> Add new Embeddings endpoint

- go.mod
Simply ran `go mod init github.com/sashabaranov/go-gpt3`.
> Init repo as go module

- README.md
[Remove deprecated code](https://github.com/sashabaranov/go-gpt3/pull/40/commits/90cb672976a808a597c5d64b510b267c316091d4)
Closes #39
> Remove deprecated code

- embeddings.go
Used to match the response as seen here: https://beta.openai.com/docs/api-reference/embeddings/create
Sorry for the closed PRs, had some weird upstream git issues.
> Add Usage for Embeddings Request

- embeddings.go
Incorrectly labelled the Ada model.
@sauceman40 Please review. You are absolutely right though. I must have misread it. But, something must be broken on my end because I wasn't erroring... 
Sorry for the inconvenience.
> Fix for Ada Model Name

- stream.go
Fixes https://github.com/sashabaranov/go-gpt3/issues/65
> Break infinite loops in case [DONE] is missing

- stream.go
- stream_test.go
> handle stream completion

- api_test.go
- chat.go
- completion.go
> Add ChatGPT API

- chat.go
Per https://platform.openai.com/docs/api-reference/chat/create
> Add the rest of the Chat Completion fields

- chat.go
- Doc: https://platform.openai.com/docs/guides/chat/introduction
> Add chat message role const

- api.go
- models.go
Maybe there are some error.
Should we change the field's name from CreatedAt to Created?
> fix json tag

- audio.go
- audio_test.go
Adds whisper-1 support as outlined in the API docs for transcription and translation https://platform.openai.com/docs/api-reference/audio
I have tried my best to use a similar style to the rest of the repo, but happy to tidy things up where necessary.
https://user-images.githubusercontent.com/4222666/222873861-61137977-dd24-45ba-b38d-950e8d240545.mp4
> Add whisper 1 support

- README.md
Adds an example for audio speech to text in README documentation.
> Add speech to text example in docs

- fine_tunes.go
#104 
- Add FineTune Structs and Requests
- Add CRUD Methods
OpenAI Spec: https://platform.openai.com/docs/api-reference/fine-tunes
> Implement the fine-tunes API

- .github/workflows/pr.yml
- README.md
> add code coverage github action

- fine_tunes.go
> Udpate some type to optimize usage

- image.go
- image_test.go
> fix issue #149

- image.go
> fixed typo for type ImageResponseDataInner

- README.md
Very happy to see Azure OpenAI support included in the project!  I thought an example of usage would be helpful.
> Update README.md with Azure OpenAI ChatGPT example

- api_test.go
- chat_stream.go
- chat_stream_test.go
- client.go
- error.go
- error_accumulator_test.go
- stream.go
- stream_test.go
> fix: chat stream resp error

- audio.go
Little PR for missing errors
https://github.com/sashabaranov/go-openai/issues/300
> Add missing error processing for audio

- README.md
> docs(readme): update format

- .github/FUNDING.yml
Hey @sashabaranov, my GitHub Sponsors application got approved! So, as we talked about before, I've made a PR to add myself to the FUNDING.yml. Check it out when you can!
> add vvatanabe to FUNDING.yml

- .github/ISSUE_TEMPLATE/feature_request.md
@sashabaranov I've created an issue template for bug reports. Could you please review the content of the template?
> chore: add an issue template for feature request

- .github/ISSUE_TEMPLATE/bug_report.md
@sashabaranov I've created an issue template for bug reports. Could you please review the content of the template?
> chore: add an issue template for bug report

- .github/PULL_REQUEST_TEMPLATE.md
I've removed the unnecessary metadata at the top of the pull request template. Unlike issue templates, this metadata gets rendered as markdown and is quite noisy.
**Tests**
None
None
@sashabaranov
> docs: remove medatada in PULL_REQUEST_TEMPLATE.md

- client_test.go
- fine_tuning_job.go
- fine_tuning_job_test.go
Added support for the listing of fine-tuning jobs.
Essentially copied and modified the fine-tuning events listing code that was already present.
**Tests**
Added unit test.
Add any other context or screenshots or logs about your pull request here. If the pull request relates to an open issue, please link to it.
Issue: #488
> fine tuning job listing

- README.md
Copy-pasting the old sample caused compilation errors
> Fix typo in README: AdaEmbeddingV2

- chat_test.go
> Fix typo in chat_test.go

- image.go
Added support for createImage Azure DALL-E 3 models.
> Added support for createImage Azure models

- completion.go
- embeddings.go
January 25, 2024 models update
https://openai.com/blog/new-embedding-models-and-api-updates
Added new constants 
**Tests**
manual
> Support January 25, 2024, models update

- completion.go
> Add GPT3Dot5Turbo0125 model

- speech.go
Describe the change
Added support for CreateSpeech Azure TTS&TTSHD models.
> Added support for CreateSpeech Azure models

- completion.go
Add the latest version of GPT-4-Turbo const
> feat: add GPT4Turbo and GPT4Turbo20240409

- README.md
- assistant.go
- client_test.go
- error.go
This PR fixes a few typos I spotted in the project.
With this PR applied all results of the [Go report card](https://goreportcard.com/report/github.com/sashabaranov/go-openai) for this project are at 100%.
> Fixing typos

- api_internal_test.go
- client.go
- config.go
Add test for #700 .
https://developers.cloudflare.com/ai-gateway/providers/azureopenai/
> feat: support cloudflare AI Gateway flavored azure openai

- README.md
Added DALL.E 3 to readme.md as its supported now as per issue https://github.com/sashabaranov/go-openai/issues/494
Added DALL.E 3 to readme.md
PR: https://github.com/sashabaranov/go-openai/issues/494
Provide a relevant …
> Added DALL.E 3 to readme.md

- .github/workflows/integration-tests.yml
Continuing the work in https://github.com/sashabaranov/go-openai/pull/762 to actually run integration tests when we merge to the `master` branch.
> run integration tests

- files.go
> fix: file not closed after CreateFile

- completion.go
> feat: Add GPT-4o Mini model support

- completion.go
Please provide a clear and concise description of the changes you're proposing. Explain what problem it solves or what feature it adds.
Provide a relevant API doc from https://platform.openai.com/docs/api-reference …
> Add support for `gpt-4o-2024-08-06`

- completion.go
> feat: Completion request support seed

- common.go
referenced document: https://platform.openai.com/docs/api-reference/chat/object#chat/object-usage
> feat: usage struct add CompletionTokensDetails

- assistant.go
Added missing fields to Assistent struct.
https://platform.openai.com/docs/api-reference/assistants/object
Updated Assistent struct based on OpenAI docs. Also synced order based on docs.
> fix: Updated Assistent struct with latest fields based on OpenAI docs

- messages.go
Added image URL support in Message content struct
> ref: add image url support to messages
